# .github/workflows/aws.yaml
name: AWS ECR
# on: workflow_dispatch
on: 
 push:
    branches: ci
permissions:
      id-token: write
      contents: read
jobs:
  aws:
    runs-on: ubuntu-latest
    
    steps:  
    
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::195652531345:role/ginroot-ecr-gha
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GINROOT }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_GINROOT }}
        role-session-name: ECRSession       
     
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build, tag, and push PostgreSQL custom docker image
       env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ginroot-template-service
        IMAGE_TAG: ${{ github.sha }}
       run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG postgres
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG        
        
       

        
